### ISSUE TITLE
Unable to run command on MacBook

### ISSUE THREAD

**Issue by exrme18** [frida/frida-compile#11]
Hi,
I have installed the Frida-compile instructed on readme page but while running the command I am getting following error. 

exrme:frida-uikit manish$ frida-compile
-bash: frida-compile: command not found 

Thanks

**Comment by oleavr** [comment]
This module is not meant to be installed globally. That's actually strongly discouraged, as different projects may want different versions of frida-compile. If you want to use it on the CLI, add `$(pwd)/node_modules/.bin` to your PATH. Full example on how to use frida-compile [here](https://github.com/oleavr/frida-agent-example).

**Comment by lalokupfer** [comment]
Hi,
I installed:
 pip install Frida
pip install frida-tools
npm install frida-compile
On windows 10.
but when trying to execute:
frida-compile -O compiled.js server.js
From this example:https://github.com/SebastienWae/tiktok-gorgon-bridge

I get 'frida-compile' is not recognized as an internal or external command,
operable program or batch file.
could you please help?

**Comment by oleavr** [comment]
@lalokupfer The `frida-compile` executable is in `node_modules\.bin\`.

**Comment by lalokupfer** [comment]
thanks a lot, found it and comiled. What Android emulator works best with Frida server?
Something you would recommend?

**Comment by kattakkat** [comment]
> @lalokupfer The `frida-compile` executable is in `node_modules\.bin\`.

What if it is not?
