### ISSUE TITLE
How to make script's variables available in Frida command-line?

### ISSUE THREAD

**Issue by MarSoft** [frida/frida-compile#16]
When I use regular (non-compiled) script in Frida like `frida -H ... ... -l myscript.js`, I can then access the global variables which were declared in the script from the Frida's command line.
But variables in the compiled script stay in the inner scope and cannot be accessed from command line.
How do I "export" them from compiled script?
For now the only way I could find is to manually edit compiled script which is definitely not nice.
Sorry if it is a noob question.

**Comment by oleavr** [comment]
`global.foo = foo;`

**Comment by oleavr** [comment]
(Hopefully we'll eventually have some better docs on frida-compile 😅)
