### ISSUE TITLE
Commit after 7af778112cf21772ab110594d65879f0f6077b83 breaks Brida compatibility

### ISSUE THREAD

**Issue by dtql** [frida/frida-compile#23]
Brida (https://github.com/federicodotta/Brida) uses frida-compile as a dependency. With the changes after commit 7af778112cf21772ab110594d65879f0f6077b83, the -x argument option is dropped and causes frida-compile to fail as Brida uses the '-x' option.

Using the 7af778112cf21772ab110594d65879f0f6077b83 branch appear to be working.

**Comment by oleavr** [comment]
This will be resolved once Brida upgrades to Frida 14.
