### ISSUE TITLE
WeakRef collides with esnext proposal

### ISSUE THREAD

**Issue by ChiChou** [frida/frida-compile#26]
```
  "devDependencies": {
    "@types/frida-gum": "^15.3.0",
    "@types/node": "^13.7.0",
    "frida-compile": "^10.0.0"
  }
```

I noticed that there was a new feature in esnext called WeakRef, while frida has a feature that has the same name.

https://github.com/microsoft/TypeScript/blob/bd1d8e5/src/lib/esnext.weakref.d.ts

It makes TypeScript uncompilable.

`TypeScript error: H:/Grapefruit/agent/node_modules/@types/frida-gum/index.d.ts(4669,19): Error TS2300: Duplicate identifier 'WeakRef'.`

**Comment by puppywang** [comment]
Same issue here.

**Comment by liamdawson** [comment]
I ran into this, worked around the issue by setting `lib` in the tsconfig.json (of the consuming project) to `es2020`. See https://github.com/Ayrx/trace_registernatives/pull/2 for an example.

**Comment by huan** [comment]
I run into this problem with the following versions:

```json
  "devDependencies": {
    "@types/frida-gum": "^16.5.0",
    "@types/node": "^15.12.4",
    "frida-compile": "^10.2.4",
    "typescript": "^4.3.4"
  },
  "dependencies": {
    "frida": "^14.2.18"
  }
```
