### ISSUE TITLE
Duplicate identifier `File` in frida-gum

### ISSUE THREAD

**Issue by wizche** [frida/frida-compile#27]
When compiling a simple script I get:
```
  message:
   '/home/test/node_modules/@types/frida-gum/index.d.ts(2200,15): Error TS2300: Duplicate identifier \'File\'.',
  fileName:
  '/home/test/node_modules/@types/frida-gum/index.d.ts',
```
Adding `"skipLibCheck": true` to the tsconfig.json fixes (apparently) the problem, not sure its the right way though.

I used the same package.json deps as in the agent example:
```
    "@types/frida-gum": "^16.3.0",
    "@types/node": "^14.14.22",
    "frida-compile": "^10.0.0"
```

**Comment by oleavr** [comment]
Perhaps `dom` is included in `lib` in your `tsconfig.json`? Also make sure you target `es2020`, as that's the newest spec that QuickJS supports.

**Comment by wizche** [comment]
Ciao Ole, ur first guess was the right one, removing "lib" and also the "skipLibCheck" did the job!
Thanks for the prompt help!
