### ISSUE TITLE
Parse error with "let"

### ISSUE THREAD

**Issue by uullrich** [frida/frida-compile#29]
Hello,

I have a problem with the ES6 let Keyword. It always results in a parse error.

At first I have tried to "compile" this sample:
[https://frida.re/news/2016/10/25/frida-8-1-released/](url)

At least I also have trouble with this litte code snippet:
`let a = 42;
console.log("Hello World", a);`

frida-compile does not transpile the let keyword for me. 

After the script startup with Frida it results in: Failed to load script: script(line 46): SyntaxError: parse error 

I am relatively new to frida and would be very thankful for any hint.

Version: 10.1.0

**Comment by oleavr** [comment]
Hey,

There is no longer any need to transpile to legacy syntax. The latest frida-compile doesn't do this anymore, as both QuickJS and V8 runtimes support modern syntax.

Cheers!
