### ISSUE TITLE
ParseError: 'import' and 'export' may appear only with 'sourceType: module

### ISSUE THREAD

**Issue by federicodotta** [frida/frida-compile#30]
Hi!

With last versions of frida-compile I obtain again the exception "ParseError: 'import' and 'export' may appear only with 'sourceType: module'" that was fixed in https://github.com/frida/frida-compile/pull/13.

By looking at the code in the repository it seems that the fix code in the pull request https://github.com/frida/frida-compile/pull/13. is not present. Am I wrong?

Thank you a lot for your support and for your great job!

**Comment by gergesh** [comment]
If you encounter this issue while trying to include dependencies from npm, try `npm install`ing them prior to running `frida-build`.

**Comment by federicodotta** [comment]
Solved changing the import/export syntax in my NodeJS code from ES6 to ES5 as described [here](https://marketplace.visualstudio.com/items?itemName=tlevesque.import-to-require).

Federico
