### ISSUE TITLE
Error compiling on MacOS v11.5.1

### ISSUE THREAD

**Issue by MajorD4m4ge** [frida/frida-compile#39]
Trying to compile Frida-compile via:

 npm install frida-compile@10.2.4 
 and
 make gum-macos NODE=/usr/local/bin/node (From Frida source)

npm ERR! code ETARGET
npm ERR! notarget No matching version found for frida-compile@^10.2.4.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

**Logfile output:**
49 verbose cwd /Users/user/apps/frida/frida-gum/bindings/gumjs
50 verbose Darwin 20.6.0
51 verbose argv "/usr/local/Cellar/node/16.6.0/bin/node" "/usr/local/bin/npm" "install"
52 verbose node v16.6.0
53 verbose npm  v7.19.1
54 error code ETARGET
55 error notarget No matching version found for frida-compile@^10.2.4.
56 error notarget In most cases you or one of your dependencies are requesting
56 error notarget a package version that doesn't exist.

**Comment by oleavr** [comment]
Not able to reproduce. Please try the latest version. Cheers!
