### ISSUE TITLE
unable to use import statement

### ISSUE THREAD

**Issue by commonuserlol** [frida/frida-compile#66]
hello, i ran into a problem when i wanted to refactor my code, the fact is that when i add the `import "./utils.ts"` (or any other file) to the `index.ts` (main file) i get a compilation error
```
frida -Uf com.android.support -l index.ts --runtime v8 --keepalive-interval 30
     ____
    / _  |   Frida 16.0.17 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at https://frida.re/docs/home/
   . . . .
   . . . .   Connected to Redmi Note 9 (id=)
Compiling index.ts...
Failed to bundle: ReferenceError: process is not defined
```
after that, the REPL dies, no messages are displayed like `Process teminated` or `Device lost` in other words, the console freezes

pc: windows 10 x64
using lastest frida-server (16.0.17) on android 13 with magisk 26.1

**Comment by ExternalAddress4401** [comment]
Importing simply doesn't work and hasn't for a while now: https://github.com/frida/frida-compile/issues/59

Don't expect a fix. Give up and go back to version 10 if you can.

**Comment by ExternalAddress4401** [comment]
https://github.com/frida/frida-compile/issues/55#issuecomment-1258437815

Yes it really needs to be `.js` and yes it's ridiculous that you have to go into closed Github issues to figure this out.

**Comment by aoaostar** [comment]
> [#55 (comment)](https://github.com/frida/frida-compile/issues/55#issuecomment-1258437815)
> 
> You need to have the .js extension.

Excuse me, how to automatically add the .js suffix in the pycharm configuration import?

It's troublesome to add it manually every time, I configured it but it doesn't work.
Thank you!
![image](https://user-images.githubusercontent.com/86001674/234742310-20bed759-6d61-4f73-b474-4ed95129c426.png)
