### ISSUE TITLE
createSingleFileWatcherPerName was removed with TypeScript 4.9

### ISSUE THREAD

**Issue by P-Sc** [frida/frida-compile#67]
The following line throws an error on `npm install`, because `createSingleFileWatcherPerName`was removed in microsoft/TypeScript@fd05c0cc6da676c5b9183ad2a7ced7ce363b855a .
https://github.com/frida/frida-compile/blob/1567c9595e607928312030512605ea92a29e8d14/src/system/node.ts#L80

**Comment by oleavr** [comment]
Oops! Thanks a lot for reporting this. Just released 16.2.1 with the [fix](https://github.com/frida/frida-compile/commit/3b2ce92ac4bb1a8f6661d2b0a93dd1705a0294df).
