### ISSUE TITLE
How can I create intrinsics with a Frida script?

### ISSUE THREAD

**Issue by Myles1** [frida/frida-compile#75]
I'm trying to call a function that has an argument with type `__m128i *`. How should I go about creating an instance of that intrinsic with a Frida script?

For reference, I am an android and working on a c++ binary.
I found some info on this datatype here: http://portal.nacad.ufrj.br/online/intel/compiler_c/common/core/GUID-7478B278-2240-44D8-B396-1DC508E3656E.htm

**Comment by oleavr** [comment]
You can generate an adapter function that you call using `NativeFunction`. There's some example code in [this](https://www.youtube.com/watch?v=9cr4gOPFN4o) short video. Note that the particular Writer you end up using may not support all the instructions you need -- in that case you can use an external assemble (e.g. rasm2), and `putBytes()` / `putInstruction()`.

**Comment by Myles1** [comment]
Thank you for that link!
Am I understanding correctly that I'll need to create that variable directly with assembly? To be honest, I might be too new with Frida to be able to use that code snippit correctly. Is there a more a complete example for creating an intrinsic, passing it to a function, then reading the result value?

**Comment by Myles1** [comment]
In case someone else finds this, I solved the issue by just allocating the right size for that variable and passing that instead.
