### ISSUE TITLE
Decompile

### ISSUE THREAD

**Issue by MrNom4ik** [frida/frida-compile#86]
Is it possible to decompile the library obtained by this compiler back into agent js code?

**Comment by thomasync** [comment]
> Is it possible to decompile the library obtained by this compiler back into agent js code?

hi, have you found a way to do that ?

**Comment by MrNom4ik** [comment]
> hi, have you found a way to do that ?
I haven't tried, but in theory it should be there

**Comment by Quarx2k** [comment]
> > Is it possible to decompile the library obtained by this compiler back into agent js code?
> 
> hi, have you found a way to do that ?

Hello, do you find way to restore original js script?

**Comment by MrNom4ik** [comment]
No (but I wasn't even looking)

ср, 11 сент. 2024 г., 17:04 Nickolay Semendyaev ***@***.***>:

**Comment by soufgameyt** [comment]
so did you ever found out and if you did can you explain me?

**Comment by vileforgotten** [comment]
> so did you ever found out and if you did can you explain me?

this is different from what i or kitenok use to  compile scripts, reversing this won't help you

**Comment by MrNom4ik** [comment]
> I suppose you did

Nope
